### ISSUE TITLE
What is the purpose of this project?

### ISSUE THREAD

**Issue by technoplato** [dancancro/questions#1]
Hey, came across this project from a link in the NextJS chat about hooks. 

I’m working on a project called knophy (in my profile if you’re interested) that’s a content aggregation platform where voting power is determined by competency on the content itself. Competency is going to be determined by providing correct answers to community moderated content with links to supporting evidence, and so I sense a similarity between the projects and felt I’d drop in and say hey!

Anyway, going to explore your code when I get to my computer.

**Comment by dancancro** [comment]
Sorry I just saw this now. I have a github email filter and miss most messages.

Do you agree with these three claims:
1. It is best to believe as many true things as possible and as few untrue things as possible.
2. True claims have nothing to fear from questions. Indeed if something is true, nothing can confirm its truth better than satisfactory answers to hard questions.
3. The chore of thinking up good questions is not easy and leaving this up to each person is unnecessary.

This site organizes critical questions that put to the test extraordinary truth claims typically made by religious indoctrinators to children before they are equipped to critically evaluate them. I use it as a place to store and share my internet bookmarks on the topics related to religion and to contribute withering social media comments as efficiently as possible. I have also used it to learn React.

It is running in production here www.stopindoctrination.org
